name: sen_rainforest_biz_project
description: ''
version: 0.0.1
author: senthilmalli.parameswaran@marksandspencer.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: senrainforestbizproject
  parentArtefactID: senthilmalliparameswaranmarksandspencercomteam
  buildSystem: wheel
  author: null
  createdAt: '2024-04-24 17:15:07'
pipelines:
  pipelines/enrich_account:
    name: enrich_account
    description: ''
    author: senthilmalli.parameswaran@marksandspencer.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-04-24 17:15:07'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-04-24 17:15:07'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-04-24T17:15:07.465863Z'
  name: plibMaven
  version: 7.1.88
  createdAt: '2024-04-24T17:15:07.465863Z'
  type: plibMaven
- modifiedAt: '2024-04-24T17:15:07.465863Z'
  name: plibPypi
  version: 1.8.15
  createdAt: '2024-04-24T17:15:07.465863Z'
  type: plibPypi
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.6
    isDefault: true
    author: null
    createdAt: '2024-04-24 17:13:48'
  '13587':
    projectUID: 13587
    projectName: course_lab_sources
    repositoryPath: gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=
    version: course_lab_sources/0.0.3
    isDefault: false
    author: null
    createdAt: '2024-04-24 17:13:48'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2024-04-24 17:13:48'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
