name: proj_test_metrics
description: ''
version: '46.2'
author: senthilmalli.parameswaran@mnscorp.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: projtestmetrics
  parentArtefactID: testsst
  buildSystem: wheel
  author: null
  createdAt: '2024-07-29 13:51:57'
pipelines:
  pipelines/pl_test_ntz:
    name: pl_test_ntz
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-07-29 13:51:57'
    datasets:
      inputs:
      - datasets/src_ds
      outputs:
      - datasets/tgt_ds
    subgraphs: []
    dependencies: {}
  pipelines/pl_test_observability:
    name: pl_test_observability
    description: testing for observability
    author: senthilmalli.parameswaran@mnscorp.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-05 11:53:57'
    datasets:
      inputs:
      - datasets/src_ds
      outputs:
      - datasets/tgt_ds
    subgraphs: []
    dependencies: {}
  pipelines/pl_observability_test_v1:
    name: pl_observability_test_v1
    description: Testing observability feature
    author: senthilmalli.parameswaran@mnscorp.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-20 11:50:14'
    datasets:
      inputs:
      - datasets/src_ds_test
      - datasets/src_ds_test_in2
      outputs:
      - datasets/tgt_ds_test
    subgraphs: []
    dependencies: {}
datasets:
  datasets/src_ds:
    name: src_ds
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    createdAt: '2024-07-30 11:41:12'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 3
        datasetType: Database
        description: ''
        author: senthilmalli.parameswaran@mnscorp.net
        createdAt: '2024-07-30 11:41:12'
  datasets/tgt_ds:
    name: tgt_ds
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    createdAt: '2024-07-30 11:43:07'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 3
        datasetType: Database
        description: ''
        author: senthilmalli.parameswaran@mnscorp.net
        createdAt: '2024-07-30 11:43:07'
  datasets/src_ds_test:
    name: src_ds_test
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    createdAt: '2024-08-20 11:51:33'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 3
        datasetType: Database
        description: ''
        author: senthilmalli.parameswaran@mnscorp.net
        createdAt: '2024-08-20 11:51:33'
  datasets/tgt_ds_test:
    name: tgt_ds_test
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    createdAt: '2024-08-20 11:55:06'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 3
        datasetType: Database
        description: ''
        author: senthilmalli.parameswaran@mnscorp.net
        createdAt: '2024-08-20 11:55:06'
  datasets/src_ds_test_in2:
    name: src_ds_test_in2
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    createdAt: '2024-08-20 12:57:21'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 3
        datasetType: Database
        description: ''
        author: senthilmalli.parameswaran@mnscorp.net
        createdAt: '2024-08-20 12:57:21'
templates: {}
jobs:
  jobs/Job_test_observability:
    name: Job_test_observability
    description: ''
    fabricUID: 13
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 6 18 * * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2024-08-06 08:58:40'
    author: senthilmalli.parameswaran@mnscorp.net
    models: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-07-29 13:51:57'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-08-20T13:33:15.651565Z'
  name: plibMaven
  version: 8.0.29
  id: '369041759'
  createdAt: '2024-08-20T13:33:15.651484Z'
- type: plibPypi
  modifiedAt: '2024-08-20T13:33:15.651594Z'
  name: plibPypi
  version: 1.9.9
  id: '320894472'
  createdAt: '2024-08-20T13:33:15.651588Z'
projectDependencies:
  '52':
    projectUID: 52
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/5qX7Px4b_team_37/5qX7Px4b_project_52.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-08-19 15:05:11'
  '51':
    projectUID: 51
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/5qX7Px4b_team_37/5qX7Px4b_project_51.git&subPath=
    version: 0.2.25
    isDefault: true
    author: null
    createdAt: '2024-08-19 15:05:11'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
