name: proj_test_metrics
description: ''
version: 0.0.1
author: senthilmalli.parameswaran@mnscorp.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: projtestmetrics
  parentArtefactID: testsst
  buildSystem: wheel
  author: null
  createdAt: '2024-07-29 13:51:57'
pipelines:
  pipelines/pl_test_ntz:
    name: pl_test_ntz
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-07-29 13:51:57'
    datasets:
      inputs:
      - datasets/src_ds
      outputs:
      - datasets/tgt_ds
    subgraphs: []
    dependencies: {}
datasets:
  datasets/src_ds:
    name: src_ds
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    createdAt: '2024-07-30 11:41:12'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 3
        datasetType: Database
        description: ''
        author: senthilmalli.parameswaran@mnscorp.net
        createdAt: '2024-07-30 11:41:12'
  datasets/tgt_ds:
    name: tgt_ds
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    createdAt: '2024-07-30 11:43:07'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 3
        datasetType: Database
        description: ''
        author: senthilmalli.parameswaran@mnscorp.net
        createdAt: '2024-07-30 11:43:07'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-07-29 13:51:57'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-07-29T13:51:57.292227Z'
  name: plibMaven
  version: 8.0.29
  id: '2040829212'
  createdAt: '2024-07-29T13:51:57.292227Z'
  type: plibMaven
- modifiedAt: '2024-07-29T13:51:57.292227Z'
  name: plibPypi
  version: 1.9.9
  id: '1903410798'
  createdAt: '2024-07-29T13:51:57.292227Z'
  type: plibPypi
projectDependencies:
  '52':
    projectUID: 52
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/5qX7Px4b_team_37/5qX7Px4b_project_52.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-07-29 14:36:18'
  '51':
    projectUID: 51
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/5qX7Px4b_team_37/5qX7Px4b_project_51.git&subPath=
    version: 0.2.25
    isDefault: true
    author: null
    createdAt: '2024-07-29 14:36:18'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
