name: proj_test_metrics
description: ''
version: '28.4'
author: senthilmalli.parameswaran@mnscorp.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: projtestmetrics
  parentArtefactID: testsst
  buildSystem: wheel
  author: null
  createdAt: '2024-07-29 13:51:57'
pipelines:
  pipelines/pl_test_ntz:
    name: pl_test_ntz
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-07-29 13:51:57'
    datasets:
      inputs:
      - datasets/src_ds
      outputs:
      - datasets/tgt_ds
    subgraphs: []
    dependencies: {}
  pipelines/pl_test_observability:
    name: pl_test_observability
    description: testing for observability
    author: senthilmalli.parameswaran@mnscorp.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-05 11:53:57'
    datasets:
      inputs:
      - datasets/src_ds
      outputs:
      - datasets/tgt_ds
    subgraphs: []
    dependencies: {}
  pipelines/pl_observability_test_v1:
    name: pl_observability_test_v1_all_sampling
    description: Testing observability feature
    author: senthilmalli.parameswaran@mnscorp.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-20 11:50:14'
    datasets:
      inputs:
      - datasets/src_ds_test
      - datasets/src_ds_test_in2
      outputs:
      - datasets/tgt_ds_test
    subgraphs: []
    dependencies: {}
  pipelines/testcopilot:
    name: testcopilot
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-09-20 08:41:53'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/pl_observability_test_v1_InputOnly:
    name: pl_observability_test_v1_source
    description: null
    author: senthilmalli.parameswaran@mnscorp.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-10-14 22:19:42'
    datasets:
      inputs:
      - datasets/src_ds_test
      - datasets/src_ds_test_in2
      outputs:
      - datasets/tgt_ds_test
    subgraphs: []
    dependencies: {}
  pipelines/pl_observability_test_v1_targets:
    name: pl_observability_test_v1_targets
    description: null
    author: senthilmalli.parameswaran@mnscorp.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-10-14 22:23:26'
    datasets:
      inputs:
      - datasets/src_ds_test
      - datasets/src_ds_test_in2
      outputs:
      - datasets/tgt_ds_test
    subgraphs: []
    dependencies: {}
  pipelines/pl_observability_test_v1_io:
    name: pl_observability_test_v1_io
    description: null
    author: senthilmalli.parameswaran@mnscorp.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-10-14 22:25:30'
    datasets:
      inputs:
      - datasets/src_ds_test
      - datasets/src_ds_test_in2
      outputs:
      - datasets/tgt_ds_test
    subgraphs: []
    dependencies: {}
  pipelines/pl_observability_test_v1_vanilla:
    name: pl_observability_test_v1_vanilla
    description: null
    author: senthilmalli.parameswaran@mnscorp.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-10-14 22:27:46'
    datasets:
      inputs:
      - datasets/src_ds_test
      - datasets/src_ds_test_in2
      outputs:
      - datasets/tgt_ds_test
    subgraphs: []
    dependencies: {}
  pipelines/pl_observability_test_v1_jobsampling_disabled:
    name: pl_observability_test_v1_jobsampling_disabled
    description: null
    author: senthilmalli.parameswaran@mnscorp.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-10-14 22:32:36'
    datasets:
      inputs:
      - datasets/src_ds_test
      - datasets/src_ds_test_in2
      outputs:
      - datasets/tgt_ds_test
    subgraphs: []
    dependencies: {}
  pipelines/pls_metrics_ops_v1:
    name: pls_metrics_ops_v1
    description: Operations frequent issues observability test
    author: senthilmalli.parameswaran@mnscorp.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-10-22 04:04:27'
    datasets:
      inputs:
      - datasets/src_tbl_pq_metrics_test2
      outputs:
      - datasets/tgt_tbl_pq_metric_r1
    subgraphs: []
    dependencies: {}
  pipelines/pl_metrics_ops_v2:
    name: pl_metrics_ops_v2
    description: Merge conflict
    author: senthilmalli.parameswaran@mnscorp.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-10-28 12:19:44'
    datasets:
      inputs:
      - datasets/src_tbl_pq_metrics_test2
      outputs:
      - datasets/tgt_tbl_metric3
    subgraphs: []
    dependencies: {}
  pipelines/pl_metrics_ops_v3:
    name: pl_metrics_ops_v3
    description: File unavailability
    author: senthilmalli.parameswaran@mnscorp.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-10-28 15:42:35'
    datasets:
      inputs:
      - datasets/src_csv_metric3
      outputs:
      - datasets/tgt_tbl_insert_metric3
    subgraphs: []
    dependencies: {}
  pipelines/pl_metrics_ops_v4:
    name: pl_metrics_ops_v4
    description: SQL Server connection issue
    author: senthilmalli.parameswaran@mnscorp.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-10-28 17:48:48'
    datasets:
      inputs:
      - datasets/src_csv_metric3
      outputs:
      - datasets/tgt_tbl_insert_metric3
    subgraphs: []
    dependencies: {}
datasets:
  datasets/src_ds:
    name: src_ds
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    createdAt: '2024-07-30 11:41:12'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 3
        datasetType: Database
        description: ''
        author: senthilmalli.parameswaran@mnscorp.net
        createdAt: '2024-07-30 11:41:12'
  datasets/tgt_ds:
    name: tgt_ds
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    createdAt: '2024-07-30 11:43:07'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 3
        datasetType: Database
        description: ''
        author: senthilmalli.parameswaran@mnscorp.net
        createdAt: '2024-07-30 11:43:07'
  datasets/src_ds_test:
    name: src_ds_test
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    createdAt: '2024-08-20 11:51:33'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 3
        datasetType: Database
        description: ''
        author: senthilmalli.parameswaran@mnscorp.net
        createdAt: '2024-08-20 11:51:33'
  datasets/tgt_ds_test:
    name: tgt_ds_test
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    createdAt: '2024-08-20 11:55:06'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 3
        datasetType: Database
        description: ''
        author: senthilmalli.parameswaran@mnscorp.net
        createdAt: '2024-08-20 11:55:06'
  datasets/src_ds_test_in2:
    name: src_ds_test_in2
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    createdAt: '2024-08-20 12:57:21'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 3
        datasetType: Database
        description: ''
        author: senthilmalli.parameswaran@mnscorp.net
        createdAt: '2024-08-20 12:57:21'
  datasets/src_tbl_pq_metrics_test2:
    name: src_tbl_pq_metrics_test2
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    createdAt: '2024-10-24 04:34:45'
    mode: batch
    physicalDatasets:
      ndev:
        fabricId: 3
        datasetType: Database
        description: ''
        author: senthilmalli.parameswaran@mnscorp.net
        createdAt: '2024-10-24 04:34:45'
  datasets/tgt_tbl_pq_metric_r1:
    name: tgt_tbl_pq_metric_r1
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    createdAt: '2024-10-24 04:38:53'
    mode: batch
    physicalDatasets:
      ndev:
        fabricId: 3
        datasetType: Database
        description: ''
        author: senthilmalli.parameswaran@mnscorp.net
        createdAt: '2024-10-24 04:38:53'
  datasets/tgt_tbl_metric3:
    name: tgt_tbl_metric3
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    createdAt: '2024-10-28 12:52:16'
    mode: batch
    physicalDatasets:
      fbr_dbr_ndev:
        fabricId: 13
        datasetType: Database
        description: ''
        author: senthilmalli.parameswaran@mnscorp.net
        createdAt: '2024-10-28 12:52:16'
  datasets/src_csv_metric3:
    name: src_csv_metric3
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    createdAt: '2024-10-28 16:01:50'
    mode: batch
    physicalDatasets:
      fbr_dbr_ndev:
        fabricId: 13
        datasetType: File
        description: ''
        author: senthilmalli.parameswaran@mnscorp.net
        createdAt: '2024-10-28 16:01:50'
  datasets/tgt_tbl_insert_metric3:
    name: tgt_tbl_insert_metric3
    description: ''
    author: senthilmalli.parameswaran@mnscorp.net
    createdAt: '2024-10-28 16:08:17'
    mode: batch
    physicalDatasets:
      fbr_dbr_ndev:
        fabricId: 13
        datasetType: Database
        description: ''
        author: senthilmalli.parameswaran@mnscorp.net
        createdAt: '2024-10-28 16:08:17'
templates: {}
jobs:
  jobs/Job_test_observability:
    name: Job_test_observability
    description: ''
    fabricUID: 13
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 6 18 * * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2024-08-06 08:58:40'
    author: senthilmalli.parameswaran@mnscorp.net
    models: []
    sqlProjects: []
  jobs/test1:
    name: test1
    description: sample
    fabricUID: 3
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1 * ? *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/pls_metrics_ops_v1
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-10-24 05:11:04'
    author: senthilmalli.parameswaran@mnscorp.net
    models: []
    sqlProjects: []
  jobs/test2:
    name: test2
    description: test
    fabricUID: 13
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 1 * *
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines:
    - pipelines/pl_metrics_ops_v4
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-10-28 19:10:30'
    author: senthilmalli.parameswaran@mnscorp.net
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-07-29 13:51:57'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-10-28T17:48:49.512224Z'
  name: plibMaven
  version: 8.0.31
  id: '150211797'
  createdAt: '2024-10-28T17:48:49.512193Z'
  enabled: true
  entity: Project
- type: plibPypi
  modifiedAt: '2024-10-28T18:21:55.952Z'
  name: ProphecyLibsPython
  version: 1.9.9
  id: '1910559264'
  createdAt: '2024-10-28T17:48:49.512248Z'
  enabled: true
  entity: Project
  description: Default dependency for Prophecy Libs
  scope: Project
  editable: true
projectDependencies:
  '52':
    projectUID: 52
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/5qX7Px4b_team_37/5qX7Px4b_project_52.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-10-04 08:52:37'
  '51':
    projectUID: 51
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/5qX7Px4b_team_37/5qX7Px4b_project_51.git&subPath=
    version: 0.2.28
    isDefault: true
    author: null
    createdAt: '2024-10-14 21:58:26'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
